### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by Rambo-Junior** [L4ki/Gently#1]
Hi,

I can't install the theme following error comes up:

Installation of /tmp/oYUuqX-Gently.tar.gz failed: Could not install dependency: 'kns://wallpaper.knsrc/api.kde-look.org/1241434'

OS: Kubuntu 21.10 x86_64 
Kernel: 5.13.0-21-generic 
DE: Plasma 5.23.3 
WM: KWin 

Could you please help me out how can I resolve this?

Thanks and best regards,
R Jr.

**Comment by L4ki** [comment]
Hi RamnoJunior,

Thank you for the information.

The problem is Wallpaper authors Charlie Henson, which was removed with "Opendesktop". Today I will update the Global Theme "Gently" 

Thanks and best regards,

l4k1

**Comment by Rambo-Junior** [comment]
Hi L4ki,

Thank you, will try to do the install couple of hours later.

Best,
R Jr.
