### ISSUE TITLE
Battery icon showing as charging when its not.

### ISSUE THREAD

**Issue by monsiu** [L4ki/Gently#2]
The battery icon indicates its charging when its clearly not and it does not show capacity visually only shows the thunderbolt within the battery icon.

Its been consistent since last install till when i came back to the theme today.

**Comment by L4ki** [comment]
Hi monsui, 

Icon battery.svg, has not been changed for more than three years. I really don't know what happened at yours.

I will check in more detail.

**Comment by monsiu** [comment]
Let me give a bit of clarification.
I mean that the theme changes the battery icon from the default to the gentley one

Now the gently one am seeing it has the dots on the side to indicate capacity though am not sure if gently is supposed to have that always or if it is supposed to have more of a traditional battery icon when unplugged.

Basically this is what im seeing when plugged in and when im not...

![Screenshot_20221101_155038.png](https://user-images.githubusercontent.com/69597591/199236845-dcd6da82-85b5-4222-bac3-0dcb82583a4f.png)

**Comment by L4ki** [comment]
Hi monsiu,

I think the battery icon works well.

However, if you don't match this battery icon, I suggest you do the following: Home (Show Hidden files) > .local > share > plasma > desktoptheme > Gently > icons. Find the battery.svg icon and delete it. Gently Theme will download the default icon from Breeze Theme.
