### ISSUE TITLE
Wrong Theme Breaks Install From GUI

### ISSUE THREAD

**Issue by weignerg** [L4ki/Gently#3]
The wrong theme is uploaded to this listing for Gently.

![image](https://user-images.githubusercontent.com/29870826/203427691-af53d9ae-7bd7-463d-8b22-435a55f023cb.png)

**Comment by L4ki** [comment]
Hi weignerg,

Thank you very much, I just corrected the mistake.

**Comment by weignerg** [comment]
Love the Theme.
Thank you!
