### ISSUE TITLE
any kde5 version?

### ISSUE THREAD

**Issue by ExileFox** [L4ki/Gently#4]
I've been skimming some commit history but didn't find where kde5 support ended.

I can select this theme in qt6settings but not in qt5settings and i need something for a qt5 fallback that's not a light theme.

Thanks in advance.

**Comment by L4ki** [comment]
Hi Ryder,

"Gently-Dark-Global-6" (For Plasma 6): https://store.kde.org/p/2136791

"Gently Global Theme" (For Plasma 5): https://store.kde.org/p/1297266/

Greetings,

**Comment by ExileFox** [comment]
Ah, thanks
